disabled_rules: # rule identifiers to exclude from running
  - line_length
  - force_cast
  - trailing_whitespace
  - todo

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - fastlane

file_length:
  warning: 1200
  error: 1600
  ignore_comment_only_lines: true

type_body_length:
  warning: 600
  error: 800

function_body_length:
  warning: 120
  error: 160

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 4
  error: 6

cyclomatic_complexity:
  warning: 30
  error: 40

nesting:
  type_level: 2

identifier_name:
  min_length: 2
